### ISSUE TITLE
What is Manager Config for?

### ISSUE THREAD

**Issue by tomtomsen** [enygma/expose#24]
Im not quite sure, what's the purpose of the \Expose\Config class. 
It is used in Manager, where you can set and get it, but it doesn't seem to be used ever.

Coulnd't it be removed?

**Comment by enygma** [comment]
It's used in the `Manager` to contain the settings during execution (see https://github.com/enygma/expose/blob/09500d508fe960d30a65edcdfe51a6f74f7a8072/src/Expose/Manager.php#L553)
