### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by deviantintegral** [enygma/expose#29]
Any chance of getting a new release rolled? I'd rather not have to fork just to create a tag.

https://github.com/enygma/expose/commit/caaeb87b12c01e65ae26b2b74f83b16126f42d90 in particular prevents using this library to notify about possible intrusion attempts.

**Comment by enygma** [comment]
Oh wow - so sorry about that! I thought I'd tagged it forever ago. Let me do that now.

**Comment by enygma** [comment]
There you go - v2.2 is all set!

**Comment by deviantintegral** [comment]
Thanks @enygma ! I'm working on a Drupal module to integrate with Expose, and this unblocks that work. Looking forward to trying the new release out.

**Comment by enygma** [comment]
Closing out this issue as the release was made - thanks!
