### ISSUE TITLE
Bump Twig Version Requirement

### ISSUE THREAD

**Issue by quantumpacket** [enygma/expose#30]
Right now I am using the latest version of Twig which at this time is `1.18` with `"minimum-stability": "RC"`, however Expose requires `1.13` and will cause the following error when updating via composer:

> Your requirements could not be resolved to an installable set of packages.

> Problem 1
    - Installation request for enygma/expose 2.2 -> satisfiable by enygma/expose[2.2].
    - enygma/expose 2.2 requires twig/twig 1.13.* -> no matching package found.

> Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

I can get by it by doing `"twig/twig": "1.18 as 1.13"` but that's not ideal in my opinion. I checked the Twig code for Expose and it does not appear to contain anything that could potentially break with this version bump. Can you verify on your end that is the case and please consider bumping it? Thank you.

**Comment by enygma** [comment]
See if this works :) https://github.com/enygma/expose/releases/tag/2.3

**Comment by quantumpacket** [comment]
:+1:  works great now, thanks!
