### ISSUE TITLE
How to use expose?

### ISSUE THREAD

**Issue by Mrstar** [enygma/expose#47]
from code, I think expose use symfony framework, if I want use expose to protect my website, should I setup symfony firstly? Can someone write down the steps to use expose detailedly

**Comment by quantumpacket** [comment]
Have you read https://expose.readthedocs.org/en/latest/ ?

**Comment by Mrstar** [comment]
yes,I have read it, I just don't know where to put example.php, just the same directory as expose?and than open it in the browser?

**Comment by quantumpacket** [comment]
> I want use expose to protect my website

I just want to make sure you are aware Expose is not an application to protect your system in place of proper security and best practices. It's an IDS (Intrusion Detection System) to notify you of potential attacks.

As for *installing*, it can be as simple as making sure it's the first file loaded in your application (after your autoloader file of course). This will make sure it accesses the variables you specify before anything can modify or use them, which allows you to take action upon detection before it can do any potential harm. You can also install it as a middleware.

**Comment by Mrstar** [comment]
I just write the sample code in a file example.php, then put it in the same dorectory as expose, but it seems doesn't work.

**Comment by quantumpacket** [comment]
@Mrstar Post your code and directory structure. From what I'm getting from the above is you're adding the example file to the Expose directory and expecting it to do stuff. If you're not including the example file into your application it will never be run.

**Comment by Mrstar** [comment]
![image](https://cloud.githubusercontent.com/assets/7837874/12188356/49b27700-b5ef-11e5-9428-f956826d3d3f.png)
I visit example.php in the browser, but there nothing to display, as what write in the source code, should display the impact sorce.
![image](https://cloud.githubusercontent.com/assets/7837874/12188383/b1fdb234-b5ef-11e5-9c04-b435899466f8.png)
Am I right? I think if I can make example.php run rightly, then I know how to use expose.

**Comment by quantumpacket** [comment]
When I meant post your code and directory structure I wasn't asking for screenshots. Give a hierarchal structure of your website/application which should include the webroot, where Expose is located, etc. Then post code for all places you have put Expose installation code *(with filenames and locations)*.

> I visit example.php in the browser, but there nothing to display

I have no idea what you're doing. First, the Expose directory should never be accessible from the browser. Anything in the `./vendor` directory should be outside the webroot. If you're just opening the `example.php` file directly in your browser without using a server it will not execute the PHP *(if you view-source on the page and see PHP code then you're doing it wrong)*.

> I think if I can make example.php run rightly, then I know how to use expose. 

If your application structure is not secure then using Expose will not be much help. Like I said before, it's a tool to help detect attacks, and will not replace proper security and best practices.

**Comment by Awnage** [comment]
@Mrstar expose is its own library. It is not based on Symfony. I would recommend you read my [free phparchitect article](https://www.awnage.com/2015/11/19/basic-intrusion-detection-with-expose/ ) on setting up expose.

In terms of hooking expose up to Symfony, you should check the [EventDispatcher](http://symfony.com/doc/current/components/event_dispatcher/introduction.html) component.
