### ISSUE TITLE
Bug? Regex issue with input of 1,11,11,11,120<

### ISSUE THREAD

**Issue by dustingraham** [enygma/expose#51]
There may be a bug with this input...

1,11,11,11,120<

I found this when I had a bunch of numbers separated by commas and then follwed by a <br> it gives a non well formed numerical value encountered on the convertFromJSCharcode function.

https://github.com/enygma/expose/blob/64538aae0f4fa9f479299bc2c8ac1f6b5b35f8d5/src/Expose/Converter/ConvertJS.php#L36

Note: It must be `<` and not `&lt;` in the input that goes through the IDS.

Issue also exists in the ancestor PHPIDS implementation.

I'm not exactly sure how to fix this elegantly. Maybe $char = intval($char). The problem lies in the way php does a $char <= 127 comparison when $char = "120<" it converts the string to a number by truncating the < off the end, so it passes the comparison, but then dies when chr("120<") tries to execute.

**Comment by Awnage** [comment]
Interesting.

> < and not <

Alas, I cannot get a difference between those two, they both show up as ord=60. What ord value were you trying to represent?

**Comment by dustingraham** [comment]
> < and not <

Sorry, that was incorrect. I'm not sure what happened in my post.

Try an input string of `1,11,11,11,120<` 

The regex should pull out `$char = "120<";` that passes through `$converted .= chr($char);` Which yields an `E_NOTICE ErrorException "A non well formed numeric value encountered"`

**Comment by Awnage** [comment]
Ok, I modified my test harness and see it now. Good catch.

**Comment by Awnage** [comment]
Looks like there are other chars as well: *+-=<:,./
Interesting that > does not trigger this case as it is not captured in the regex.

**Comment by Awnage** [comment]
Bah, found it. Patch forthcoming.

**Comment by Awnage** [comment]
@dustingraham please verify that this latest version works for you

**Comment by dustingraham** [comment]
Resolved. Thanks.
