### ISSUE TITLE
Impact rating

### ISSUE THREAD

**Issue by apinedac** [enygma/expose#54]
Hello!

I would like to know which is the impact level (rating), especially the max impact number that it can return.

Thank you!

**Comment by Awnage** [comment]
I think you may need to elaborate more. I have been able to generate impact values > 300 using actual attack vectors I have collected in the wild. There is no theoretical maximum value.

**Comment by apinedac** [comment]
Hello again!

Thank you for your answer, i have already generated impact values of more than 450. Also this is what I wanted to know, there is no theoretical maximum value!

Regards.
